services:
  mosquitto:
    image: eclipse-mosquitto:2.1.2-alpine
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "1883"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_interval: 1s
      start_period: 60s

  service:
    image: golang:1.27-alpine
    command: go run -v ./cmd/service
    environment:
      LOG_LEVEL: info
      BROKER_URL: mqtt://mosquitto:1883/
      CLIENT_ID: "service-1"
      GOMODCACHE: /gocache/mod
      GOCACHE: /gocache/cache
    tty: true # enables colour output in logs
    volumes:
      - ./app:/app
      - gocache:/gocache
    working_dir: /app
    depends_on:
      mosquitto:
        condition: service_healthy

  device-1:
    extends: device
    environment:
      CLIENT_ID: "device-1"
      DEVICE_ID: "device-1"

  device-2:
    extends: device
    environment:
      CLIENT_ID: "device-2"
      DEVICE_ID: "device-2"

  device-3:
    extends: device
    environment:
      CLIENT_ID: "device-3"
      DEVICE_ID: "device-3"

  device:
    image: golang:1.27-alpine
    command: go run -v ./cmd/device
    environment:
      LOG_LEVEL: info
      BROKER_URL: mqtt://mosquitto:1883/
      DEVICE_REGION: "region-a"
      DEVICE_ZONE: "zone-b"

      GOMODCACHE: /gocache/mod
      GOCACHE: /gocache/cache
    tty: true # enables colour output in logs
    volumes:
      - ./app:/app
      - gocache:/gocache
    working_dir: /app
    depends_on:
      mosquitto:
        condition: service_healthy


volumes:
  gocache: {}