version: "3"

vars:
  app_name: device
  ssh_host: tomato
  app_executable: "{{.TASKFILE_DIR}}/build/{{.app_name}}"
  broker_url: mqtt://192.168.1.195:1883

tasks:
  run-service:
    docker compose up --force-recreate service

  run-devices:
    docker compose up device-1 device-2 device-3

  test:
    deps: [start-broker]
    cmds:
      - cd app && go test -v ./...

  start-broker:
    cmds:
      - docker compose up --detach --wait mosquitto
