version: "3"

vars:
  app_name: server-app
  ssh_host: tomato
  app_executable: "{{.TASKFILE_DIR}}/build/{{.app_name}}"
  broker_url: mqtt://192.168.1.195:1883

tasks:
  build:
    cmds:
      - cd "{{.app_name}}" && GOOS=linux GOARCH=arm64 go build -o "{{.app_executable}}" .
    sources:
      - "{{.app_name}}/**"
    generates:
      - "{{.app_executable}}"

  deploy:
    deps: [build]
    sources:
      - "{{.app_executable}}"
    cmds:
      - scp "{{.app_executable}}" "{{.ssh_host}}:~/"

  run:
    deps: [deploy]
    cmds:
      - ssh "{{.ssh_host}}" GODEBUG=netdns=go BROKER_URL={{.broker_url}} "./{{.app_name}}"
